---
- name: Ensure {{ snowflake_git_dest }} exists
  ansible.builtin.file:
    state: directory
    path: "{{ snowflake_git_dest }}"
    owner: "{{ snowflake_user }}"
    group: "{{ snowflake_group }}"
    mode: 0755

- name: Clone snowflake repo
  ansible.builtin.git:
    repo: https://git.torproject.org/pluggable-transports/snowflake.git
    dest: "{{ snowflake_git_dest }}"
    update: "{{ snowflake_git_update }}"
  register: _snowflake_clone_git
  become_user: "{{ snowflake_user }}"
  become: true
  register: _snowflake_git_clone

- when: (_snowflake_git_clone.changed) or (snowflake_force_build | bool)
  block:

    - name: Download and build Go dependencies (get & build)
      ansible.builtin.command:
        cmd: go {{ item }}
      args:
        warn: false
        chdir: "{{ snowflake_go_dest }}"
      loop:
        - get
        - build
      register: _snowflake_go_get
      become_user: "{{ snowflake_user }}"
      become: true
      notify: snowflake restart systemd

    - name: Copy binary file to /usr/bin/
      ansible.builtin.copy:
        src: "{{ snowflake_go_dest }}/"
        dest: /usr/bin/
        mode: a+x
        remote_src: true
      become_user: root
      become: true
