---
# freebsd.

- name: Config pkg repo
  ansible.builtin.template:
    src: FreeBSD.conf.j2
    dest: /etc/pkg/FreeBSD.conf
    mode: 0644

- name: Install package snowflake-tor
  community.general.pkgng:
    name: snowflake-tor
    cached: true
    state: present

- name: Enable snowflake on boot
  community.general.sysrc:
    name: snowflake_enable
    state: present
    value: "YES"

- name: Start service snowflake
  ansible.builtin.service:
    name: snowflake
    state: started
