---
- tags: snowflake
  block:

    - when:
        - not ansible_distribution == 'FreeBSD'
        - not ansible_distribution_release == '13.0-RELEASE'
      block:

        - name: Include OS specific variables
          ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
          vars:
            params:
              files:
                - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.yml"
                - "{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}/main.yml"
                - "{{ ansible_distribution | lower }}.yml"
                - main.yml
              paths:
                - vars

        - name: Import Snowflake user tasks
          ansible.builtin.import_tasks: user.yml
          tags: snowflake_user

        - name: Import Snowflake install tasks
          ansible.builtin.import_tasks: install.yml
          tags: snowflake_install

        - name: Import Snowflake build tasks
          ansible.builtin.import_tasks: build.yml
          tags: snowflake_build

        - name: Import Snowflake service tasks
          ansible.builtin.import_tasks: service.yml
          tags: snowflake_service

    - name: Import FreeBSD tasks
      ansible.builtin.import_tasks: freebsd.yml
      tags: snowflake_freebsd
      when: ansible_distribution == 'FreeBSD'
